/* =============================================
   RH-DATA.JS — Base de Dados Oficial de Colaboradores
   New Time — Gestão de RH & Turnover
   Fonte: Planilha "Rh newtime.xlsx" (179 registros)
   Última atualização: 2026-03-27
   Campo 'setor' adicionado em 2026-03-27
   Setores: Produção | Expedição | Designer | Vendas | Administrativo | Facilities
============================================= */

// Converte datas do formato M/D/YY para YYYY-MM-DD
function _parseDate(s) {
  if (!s || s === '' || s === '0') return '';
  const p = String(s).trim().split('/');
  if (p.length !== 3) return '';
  const m  = p[0].padStart(2,'0');
  const d  = p[1].padStart(2,'0');
  const yy = parseInt(p[2]);
  // Ano: se <= 30 → 2000s, senão → 1900s
  const yr = yy <= 30 ? 2000 + yy : 1900 + yy;
  return `${yr}-${m}-${d}`;
}

/* ─── MAPEAMENTO CARGO → SETOR ─────────────────
   Regras:
   • Produção     : Operador, Impressor, Revisor, Ajud. Produção, Líder de Impressão/Produção, Supervisor de Produção
   • Expedição    : Expedição, Expedidor, Encarregado de Expedição, Logística, Supervisor de Estoque/Expedição, Ajud. Expedição
   • Designer     : Designer Gráfico (Jr/Pleno/Sênior), Supervisor Designer
   • Vendas       : Vendedor, Vendedora, Atendente, Assistente de Vendas, Supervisor de Designer e Vendas
   • Administrativo: RH, DP, PCP, Financeiro, Analista, Gerente, Assistente Adm., Recrutamento, Operações, Processos, Negócios, Consultor, Estágio PCP, Assistente de Processos
   • Facilities   : Limpeza, Faxineira, Manutenção de Edificações, Facilities, Ajudante Geral (não produção), 1/2 Oficial de Manutenção
─────────────────────────────────────────────── */
window._getSetorFromCargo = function(cargo) {
  if (!cargo) return 'Outros';
  const c = cargo.toLowerCase();
  // Expedição (antes de Produção para pegar "Supervisor de Estoque/Expedição")
  if (c.includes('expediç') || c.includes('expedidor') || c.includes('logística') || c.includes('logistica') || c.includes('estoque')) return 'Expedição';
  // Produção
  if (c.includes('produção') || c.includes('producao') || c.includes('operador') || c.includes('impressor') || c.includes('revisor') || c.includes('líder de impressão') || c.includes('lider de impressao') || c.includes('calandra')) return 'Produção';
  // Designer
  if (c.includes('designer') || c.includes('supervisor designer') || c.includes('supervisor de designer') && !c.includes('vendas')) return 'Designer';
  // Supervisor de Designer e Vendas → Vendas
  if (c.includes('supervisor de designer e vendas')) return 'Vendas';
  // Vendas
  if (c.includes('vendedor') || c.includes('vendedora') || c.includes('atendente') || c.includes('assistente de vendas') || c.includes('vendas')) return 'Vendas';
  // Administrativo
  if (c.includes('rh') || c.includes('dp') || c.includes('departamento pessoal') || c.includes('pcp') || c.includes('financeiro') || c.includes('analista') || c.includes('gerente') || c.includes('administrativo') || c.includes('recrutamento') || c.includes('seleção') || c.includes('operações') || c.includes('operacoes') || c.includes('processos') || c.includes('negócio') || c.includes('negocio') || c.includes('consultor') || c.includes('freelancer') || c.includes('estagiário') || c.includes('assistente de pcp') || c.includes('assistente de dep')) return 'Administrativo';
  // Facilities
  if (c.includes('limpeza') || c.includes('faxineira') || c.includes('manutenção') || c.includes('manutencao') || c.includes('facilities') || c.includes('ajudante geral') || c.includes('ajudante geral') || c.includes('1/2 oficial')) return 'Facilities';
  return 'Outros';
};

window.HR_EMPLOYEES_SEED = [
  { matricula:'3005', nome:'Ademir Romero Cassemiro',                  situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Expedição',     cargo:'Supervisor de Estoque/Expedição',           horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('7/3/23'),   diasContrato:998,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/2/83')   },
  { matricula:'3004', nome:'Adriano Ney Baccari',                      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Supervisor de Designer e Vendas',            horario:'Seg à Sex 07:30 às 17:00',                            lider:'Patrícia',    admissao:_parseDate('9/4/23'),   diasContrato:752,  demissao:_parseDate('9/25/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/7/73')   },
  { matricula:'2113', nome:'Alessandro Silva Araujo',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'',                                                    lider:'Toni',        admissao:_parseDate('2/27/25'),  diasContrato:96,   demissao:_parseDate('6/3/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/22/01') },
  { matricula:'2061', nome:'Alex Antonio dos Santos',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('7/12/24'),  diasContrato:82,   demissao:_parseDate('10/2/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/21/93')  },
  { matricula:'2161', nome:'Alexandre Germini de Souza',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 17:00',                            lider:'Wesley Reis', admissao:_parseDate('12/1/25'),  diasContrato:116,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/29/98')  },
  { matricula:'NT-JX', nome:'Alexsander Silva de Araujo',             situacao:'DESLIGADO',  jornada:'PJ',  matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico',                          horario:'Freelancer',                                          lider:'Adriano',     admissao:'',                     diasContrato:0,    demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2050', nome:'Alison Ribeiro da Silva',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('5/27/24'),  diasContrato:274,  demissao:_parseDate('2/25/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/1/96')   },
  { matricula:'2104', nome:'Ana Beatriz de Sá',                        situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Auxiliar de RH/DP',                         horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('2/14/25'),  diasContrato:210,  demissao:_parseDate('9/12/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/31/01') },
  { matricula:'3066', nome:'Ana Karoline Silva Camilo',                situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 07:30 às 17:00 e Sex até 16:30',           lider:'Ademir',      admissao:_parseDate('8/19/24'),  diasContrato:274,  demissao:_parseDate('5/20/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/6/99')   },
  { matricula:'3068', nome:'Anderson de Almeida Ferreira',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Ademir',      admissao:_parseDate('5/13/24'),  diasContrato:372,  demissao:_parseDate('5/20/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/2/77')  },
  { matricula:'2007', nome:'André Rocha Ramalho',                      situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Líder de Impressão',                        horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Carlos',      admissao:_parseDate('6/5/23'),   diasContrato:1026, demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/7/93')   },
  { matricula:'3069', nome:'Andrew de Jesus Freitas dos Santos',       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor 1',                                horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('2/5/25'),   diasContrato:203,  demissao:_parseDate('8/27/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/2/89')   },
  { matricula:'2038', nome:'Ayrton Vegas de Souza',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante Produção',                         horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('5/10/24'),  diasContrato:285,  demissao:_parseDate('2/19/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/19/99')  },
  { matricula:'2163', nome:'Brener Neves da Silva',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('12/11/25'), diasContrato:106,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/26/97')  },
  { matricula:'2073', nome:'Breno Vinicius Gonçalves dos Santos',      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('9/12/24'),  diasContrato:168,  demissao:_parseDate('2/27/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/2/03')   },
  { matricula:'2028', nome:'Bruna Pereira Barranco',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital',                         horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('3/4/24'),   diasContrato:275,  demissao:_parseDate('12/4/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/12/90')  },
  { matricula:'2146', nome:'Bruno Cruz Oliveira dos Santos',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('9/12/25'),  diasContrato:196,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/29/05')  },
  { matricula:'2082', nome:'Bruno Henrique de Carvalho',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('10/10/24'), diasContrato:89,   demissao:_parseDate('1/7/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/3/88')  },
  { matricula:'2134', nome:'Bruno Mesquita dos Reis',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('7/31/25'),  diasContrato:44,   demissao:_parseDate('9/13/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/27/94')  },
  { matricula:'2129', nome:'Caio Felipe Fernandes Silva',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('7/10/25'),  diasContrato:45,   demissao:_parseDate('8/24/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/8/96')   },
  { matricula:'2085', nome:'Caio Santos Cunha',                        situacao:'FÉRIAS',     jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 2',                    horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('10/26/24'), diasContrato:517,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/12/04')  },
  { matricula:'2086', nome:'Carlos Aparecido Onofre Junior',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('11/7/24'),  diasContrato:89,   demissao:_parseDate('2/4/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/18/88')  },
  { matricula:'0100', nome:'Carlos Eduardo Silva',                     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Gerente Administrativo de Processos',       horario:'Art. 62',                                             lider:'Patrícia',    admissao:_parseDate('4/13/23'),  diasContrato:1079, demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/3/84')   },
  { matricula:'2126', nome:'Carlos Henrique Pires de Lima',            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 1',                    horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('5/26/25'),  diasContrato:106,  demissao:_parseDate('9/9/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/1/92')  },
  { matricula:'2143', nome:'Carlos Xu',                                situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente Administrativo',                 horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Patrícia',    admissao:_parseDate('9/1/25'),   diasContrato:207,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/4/04')   },
  { matricula:'2157', nome:'Charlene Gomes de Oliveira',               situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Supervisora de Departamento Pessoal',       horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('11/24/25'), diasContrato:123,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/24/81')  },
  { matricula:'2081', nome:'Cleber Ferreira da Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('10/10/24'), diasContrato:5,    demissao:_parseDate('10/15/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/10/87')  },
  { matricula:'2046', nome:'Cleiton Silva de Oliveira',                situacao:'FÉRIAS',     jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 2',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('5/23/24'),  diasContrato:673,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/1/98')   },
  { matricula:'2119', nome:'Davi Cunha Alves de Araújo',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('4/11/25'),  diasContrato:182,  demissao:_parseDate('10/10/25'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/11/03')  },
  { matricula:'2110', nome:'Davi de Medeiros Marcelino',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Supervisor de Produção',                    horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('2/26/25'),  diasContrato:391,  demissao:_parseDate('3/24/26'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/24/94')  },
  { matricula:'2114', nome:'Davi Henrique do Amaral Campos',           situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('2/27/25'),  diasContrato:393,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/19/04')  },
  { matricula:'2069', nome:'David De Faria Santos',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Guilherme',   admissao:_parseDate('8/29/24'),  diasContrato:307,  demissao:_parseDate('7/2/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/20/87')  },
  { matricula:'2004', nome:'David Leandro Silva Santos',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital',                         horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'André',       admissao:_parseDate('4/3/23'),   diasContrato:622,  demissao:_parseDate('12/15/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/7/00')   },
  { matricula:'3056', nome:'David Neimer da Silva Coelho',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 17:00',                            lider:'Ademir',      admissao:_parseDate('8/12/24'),  diasContrato:44,   demissao:_parseDate('9/25/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/23/95')  },
  { matricula:'2156', nome:'Debora de Andrade Oliveira',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente Administrativo JR',              horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('11/17/25'), diasContrato:130,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/4/97')   },
  { matricula:'2091', nome:'Dennis William Jesus de Souza',            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Auxiliar de Logística',                     horario:'Seg à Qui 07:00 às 17:00 e Sex até 16:00',           lider:'Wesley Reis', admissao:_parseDate('11/28/24'), diasContrato:284,  demissao:_parseDate('9/8/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/27/99')  },
  { matricula:'2112', nome:'Diego Cicero de Souza Maciel',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('2/27/25'),  diasContrato:201,  demissao:_parseDate('9/16/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/8/95')   },
  { matricula:'2135', nome:'Diego Oliveira Sousa',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('8/8/25'),   diasContrato:45,   demissao:_parseDate('9/22/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/3/91')   },
  { matricula:'2053', nome:'Diego Shismytt Galvão',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante Produção',                         horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('6/6/24'),   diasContrato:74,   demissao:_parseDate('8/19/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/26/90')  },
  { matricula:'2125', nome:'Diego Silva de Freitas Rocha',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Trabalhador de Manutenção de Edificações',  horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Fernanda',    admissao:_parseDate('5/21/25'),  diasContrato:86,   demissao:_parseDate('8/15/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/9/95')  },
  { matricula:'3006', nome:'Douglas da Silva Chaves',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('5/2/24'),   diasContrato:110,  demissao:_parseDate('8/20/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/13/96')  },
  { matricula:'2105', nome:'Ed Carlos Costa das Virgens',              situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 2',                    horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Renato',      admissao:_parseDate('2/13/25'),  diasContrato:407,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/24/99')  },
  { matricula:'2031', nome:'Edson Zhu',                                situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente Administrativo',                 horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Patrícia',    admissao:_parseDate('3/4/24'),   diasContrato:753,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/14/07')  },
  { matricula:'0175', nome:'Eduarda Costa Pires',                      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente Administrativo',                 horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('10/27/25'), diasContrato:151,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/17/99') },
  { matricula:'3080', nome:'Elisa Akemi Tanaka',                       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('8/22/25'),  diasContrato:42,   demissao:_parseDate('10/3/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/18/97')  },
  { matricula:'3092', nome:'Elisa Akemi Tanaka (recontratada)',        situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('1/19/26'),  diasContrato:67,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/18/97')  },
  { matricula:'2149', nome:'Enzo Pompeu da Silva',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Estagiário de PCP',                         horario:'Seg à Sex 13:00 às 18:00',                            lider:'Wesley Cruz', admissao:_parseDate('9/18/25'),  diasContrato:190,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/7/08')  },
  { matricula:'2117', nome:'Euclides Barbosa Neto',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Trabalhador da Manutenção de Edificações',  horario:'',                                                    lider:'Fernanda',    admissao:_parseDate('4/4/25'),   diasContrato:10,   demissao:_parseDate('4/14/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/27/89')  },
  { matricula:'3090', nome:'Evelyn Vitória Vieira Lino',               situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Auxiliar de Limpeza',                       horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Vinícios',    admissao:_parseDate('1/8/26'),   diasContrato:78,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/15/95') },
  { matricula:'2109', nome:'Everton Silva Santos',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'',                                                    lider:'André',       admissao:_parseDate('2/24/25'),  diasContrato:126,  demissao:_parseDate('6/30/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/9/87')   },
  { matricula:'2092', nome:'Everton Vegas',                            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:'',                     diasContrato:0,    demissao:_parseDate('2/7/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/21/94')  },
  { matricula:'2131', nome:'Ewerton Araújo Lima',                      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('7/24/25'),  diasContrato:43,   demissao:_parseDate('9/5/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/2/98')  },
  { matricula:'3067', nome:'Fabio Geronimo Lima Pereira',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico',                          horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('12/9/24'),  diasContrato:266,  demissao:_parseDate('9/1/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2103', nome:'Felipe Fernandes Lopes',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('2/11/25'),  diasContrato:42,   demissao:_parseDate('3/25/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/31/97')  },
  { matricula:'2093', nome:'Felipe Fontes Fernandes',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('1/22/25'),  diasContrato:12,   demissao:_parseDate('2/3/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/30/97')  },
  { matricula:'2067', nome:'Felipe José da Silva',                     situacao:'DESLIGADO',  jornada:'PJ',  matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 1',                    horario:'Freelancer',                                          lider:'Samuel',      admissao:_parseDate('8/26/24'),  diasContrato:578,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/12/04')  },
  { matricula:'2065', nome:'Felipe Siqueira de Lima',                  situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 2',                                 horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Renato',      admissao:_parseDate('8/22/24'),  diasContrato:582,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/7/96')   },
  { matricula:'2078', nome:'Fernanda Rezende de Queiroz',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Analista Administrativa Senior',             horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('10/7/24'),  diasContrato:536,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/26/96')  },
  { matricula:'3007', nome:'Fernando Henrique Soares dos Santos',      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Vendas',         cargo:'Assistente de Vendas',                      horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Carlos',      admissao:_parseDate('2/1/24'),   diasContrato:257,  demissao:_parseDate('10/15/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/24/05') },
  { matricula:'2162', nome:'Flávia Karolina Trindade Souto',           situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de Recrutamento e Seleção',      horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('12/8/25'),  diasContrato:109,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/23/93')  },
  { matricula:'2014', nome:'Gabriel Moreira Leme Bustamante',          situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Designer',       cargo:'Supervisor Designer',                       horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Patrícia',    admissao:_parseDate('9/4/23'),   diasContrato:501,  demissao:_parseDate('1/17/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/18/03')  },
  { matricula:'2130', nome:'Gabriel Ribeiro da Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('7/24/25'),  diasContrato:43,   demissao:_parseDate('9/5/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/14/05') },
  { matricula:'2152', nome:'Gabriel Rodrigues de Franca',              situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Wesley Reis', admissao:_parseDate('10/6/25'),  diasContrato:172,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/5/98')   },
  { matricula:'3077', nome:'Gabriela Dimarzio',                        situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Pleno',                    horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('6/17/25'),  diasContrato:89,   demissao:_parseDate('9/14/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/14/97')  },
  { matricula:'3082', nome:'Gaspar Freires Soares de Paiva',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Ademir',      admissao:_parseDate('8/29/25'),  diasContrato:210,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/15/89')  },
  { matricula:'2137', nome:'Grace Kelly Scapim Pinto',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Supervisora de RH/DP',                      horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('8/12/25'),  diasContrato:59,   demissao:_parseDate('10/10/25'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/9/93')  },
  { matricula:'NT-CH', nome:'Guhan Tang',                              situacao:'ATIVO',      jornada:'CLT', matriz:'NT-CH', setor:'Administrativo', cargo:'Analista de Negócios',                      horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Patrícia',    admissao:_parseDate('5/15/25'),  diasContrato:316,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/12/87') },
  { matricula:'2011', nome:'Guilherme de Oliveira Capusso',            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Supervisor de Facilities',                  horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Carlos',      admissao:_parseDate('9/4/23'),   diasContrato:590,  demissao:_parseDate('4/16/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/27/97') },
  { matricula:'2107', nome:'Guilherme Ferreira Torres',                situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 1',                    horario:'',                                                    lider:'Davi',        admissao:_parseDate('2/19/25'),  diasContrato:86,   demissao:_parseDate('5/16/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/17/02') },
  { matricula:'2089', nome:'Guilherme Pereira Alves de Sousa',         situacao:'FÉRIAS',     jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('11/29/24'), diasContrato:483,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/29/01') },
  { matricula:'2034', nome:'Gustavo Cardoso da Silva',                 situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Ajudante de Expedição 2',                   horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Wesley Reis', admissao:_parseDate('5/1/24'),   diasContrato:695,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/31/01') },
  { matricula:'2155', nome:'Gustavo Henrique Oliveira Albuquerque',    situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('10/15/25'), diasContrato:163,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/1/03')   },
  { matricula:'2123', nome:'Gustavo Marques Lima',                     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('5/20/25'),  diasContrato:311,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/4/04')   },
  { matricula:'2087', nome:'Gustavo Souza do Nascimento',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de Operações',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Wesley Cruz', admissao:_parseDate('11/7/24'),  diasContrato:275,  demissao:_parseDate('8/9/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/18/84')  },
  { matricula:'2154', nome:'Heleno Ramos Crerencio',                   situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Supervisor de Produção',                    horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Carlos',      admissao:_parseDate('10/14/25'), diasContrato:164,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/28/05')  },
  { matricula:'2116', nome:'Henri Souza Santos',                       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('3/18/25'),  diasContrato:374,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/12/01')  },
  { matricula:'3073', nome:'Henrique da Silva Santos',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Pleno',                    horario:'Seg à Sex 08:00 às 17:00',                            lider:'Adriano',     admissao:_parseDate('2/13/25'),  diasContrato:90,   demissao:_parseDate('5/14/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/14/88')  },
  { matricula:'3091', nome:'Herbert de Santana',                       situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('1/19/26'),  diasContrato:67,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/3/05')   },
  { matricula:'3088', nome:'Hernes Gabriel Martinez Colmenares',       situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Ademir',      admissao:_parseDate('10/20/25'), diasContrato:158,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/20/04')  },
  { matricula:'2051', nome:'Higor dos Santos Palmeira Brandão',        situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('5/23/24'),  diasContrato:673,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/10/93') },
  { matricula:'3062', nome:'Hildon de Oliveira Rocha',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('12/3/24'),  diasContrato:86,   demissao:_parseDate('2/27/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/6/04')  },
  { matricula:'2097', nome:'Hugo Augusto dos Santos Silva',            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('2/1/25'),   diasContrato:187,  demissao:_parseDate('8/7/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/14/99')  },
  { matricula:'2036', nome:'Igor Lima Borges',                         situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('5/1/24'),   diasContrato:434,  demissao:_parseDate('7/9/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/19/97')  },
  { matricula:'2158', nome:'Ingryd Manuella Barreto',                  situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de Departamento Pessoal',        horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('11/24/25'), diasContrato:123,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/15/92')  },
  { matricula:'2075', nome:'Ivan Costa Fernandes',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('9/23/24'),  diasContrato:43,   demissao:_parseDate('11/5/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/14/06')  },
  { matricula:'2132', nome:'Jackson Almeida da Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('8/1/25'),   diasContrato:238,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/27/81')  },
  { matricula:'2055', nome:'Jefferson de Faria Pereira',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('6/7/24'),   diasContrato:89,   demissao:_parseDate('9/4/24'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/16/95')  },
  { matricula:'2088', nome:'Jefferson Lucas Souza Sorentino',          situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Trabalhador de Manutenção de Edificações',  horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Fernanda',    admissao:_parseDate('11/12/24'), diasContrato:500,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/31/97')  },
  { matricula:'3087', nome:'Jéssica Berigo Valentim Pereira',          situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('10/20/25'), diasContrato:158,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/1/97')  },
  { matricula:'NT-CH2',nome:'Jie Ding',                                situacao:'ATIVO',      jornada:'CLT', matriz:'NT-CH', setor:'Administrativo', cargo:'Analista de Negócios',                      horario:'Seg à Qui 09:30 às 17:30 e Sex até 16:30',           lider:'Patrícia',    admissao:_parseDate('4/17/25'),  diasContrato:344,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/24/04')  },
  { matricula:'2102', nome:'João Gabriel Souza Lima',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('2/7/25'),   diasContrato:413,  demissao:_parseDate('5/7/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/11/00')  },
  { matricula:'2147', nome:'João Marcos da Silva',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('9/17/25'),  diasContrato:191,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/13/90')  },
  { matricula:'3064', nome:'João Pedro Faria dos Santos',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('1/21/25'),  diasContrato:430,  demissao:_parseDate('1/21/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/19/97')  },
  { matricula:'2026', nome:'João Victor / Stephany Machado',           situacao:'DESLIGADO',  jornada:'PJ',  matriz:'NT',    setor:'Administrativo', cargo:'Freelancer',                                horario:'Freelancer',                                          lider:'Samuel',      admissao:_parseDate('2/1/24'),   diasContrato:600,  demissao:_parseDate('9/23/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/23/99')  },
  { matricula:'2060', nome:'Joelson Nascimento dos Santos',            situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('7/13/24'),  diasContrato:89,   demissao:_parseDate('10/10/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/14/04')  },
  { matricula:'2153', nome:'Johnny de Melo Jorge',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('10/13/25'), diasContrato:165,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/28/97')  },
  { matricula:'2170', nome:'Johnny Wallace Cruz de Souza',             situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('3/11/26'),  diasContrato:16,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/21/95')  },
  { matricula:'2059', nome:'Jonatan dos Santos Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('7/17/24'),  diasContrato:70,   demissao:_parseDate('9/25/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/19/99')  },
  { matricula:'2084', nome:'Jonathan Almeida de Carvalho',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('10/24/24'), diasContrato:161,  demissao:_parseDate('4/3/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/10/05')  },
  { matricula:'2090', nome:'Jonathan Araújo Jesus Dos Santos',         situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('11/28/24'), diasContrato:18,   demissao:_parseDate('12/16/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/19/83')  },
  { matricula:'2106', nome:'Jonathan Henrique Rodrigues da Silva',     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 2',                                 horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('2/13/25'),  diasContrato:407,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/3/06')   },
  { matricula:'2096', nome:'José Henrique da Silva Galvão',            situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 1',                    horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('1/25/25'),  diasContrato:426,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2124', nome:'Jose Rogerio da Silva',                    situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Supervisor de Produção',                    horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Carlos',      admissao:_parseDate('5/19/25'),  diasContrato:312,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/30/90')  },
  { matricula:'3060', nome:'Josué Ferreira Alves',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral 1',                          horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('9/11/24'),  diasContrato:301,  demissao:_parseDate('7/9/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/17/95')  },
  { matricula:'2094', nome:'Kaik Garcia',                              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('9/4/24'),   diasContrato:188,  demissao:_parseDate('3/11/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/6/01')  },
  { matricula:'2141', nome:'Leandro Jorge da Fonseca',                 situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'1/2 Oficial de Manutenção',                 horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Carlos',      admissao:_parseDate('8/19/25'),  diasContrato:220,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/10/05')  },
  { matricula:'2080', nome:'Leonardo Osmola Molozzi',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('10/10/24'), diasContrato:89,   demissao:_parseDate('1/7/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/1/96')   },
  { matricula:'2128', nome:'Leonardo Ribeiro de Sousa',                situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('6/13/25'),  diasContrato:287,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/17/93') },
  { matricula:'3059', nome:'Lorrane Lacerda Lima',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Atendente',                                 horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('8/29/24'),  diasContrato:89,   demissao:_parseDate('11/26/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/26/99')  },
  { matricula:'3078', nome:'Luan de França Silva',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Ademir',      admissao:_parseDate('8/12/25'),  diasContrato:56,   demissao:_parseDate('10/7/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/6/98')   },
  { matricula:'2048', nome:'Lucas Alves da Costa',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante Produção',                         horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('5/23/24'),  diasContrato:112,  demissao:_parseDate('9/12/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/11/99')  },
  { matricula:'2151', nome:'Lucas Gabriel Cruz dos Santos',            situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('10/3/25'),  diasContrato:175,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/2/99')  },
  { matricula:'3055', nome:'Lucas Matheus Gomes Ferreira Domingues',   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 17:00',                            lider:'Ademir',      admissao:_parseDate('8/1/24'),   diasContrato:169,  demissao:_parseDate('1/17/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/16/95')  },
  { matricula:'3061', nome:'Lucas Oliveira de Souza',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico',                          horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('10/24/24'), diasContrato:110,  demissao:_parseDate('2/11/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/19/04')  },
  { matricula:'3089', nome:'Lucas Pereira Silva',                      situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('10/23/25'), diasContrato:155,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/11/93')  },
  { matricula:'2166', nome:'Lucas Rios do Nascimento',                 situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Ajudante de Expedição',                     horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('1/26/26'),  diasContrato:60,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/25/84')  },
  { matricula:'2021', nome:'Lucas Rodrigues Da Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('10/2/23'),  diasContrato:695,  demissao:_parseDate('8/27/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/15/98')  },
  { matricula:'2148', nome:'Luis Carlos dos Santos Junior',            situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Renato',      admissao:_parseDate('9/18/25'),  diasContrato:190,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/16/97')  },
  { matricula:'2168', nome:'Luiz Alberto Morais Simon',                situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Ajudante de Expedição',                     horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('1/27/26'),  diasContrato:59,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/16/97')  },
  { matricula:'2098', nome:'Marcio Alencar de Azevedo',                situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('1/31/25'),  diasContrato:19,   demissao:_parseDate('2/19/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/22/01')  },
  { matricula:'2037', nome:'Marcos Vinicios Abade de Sousa',           situacao:'FÉRIAS',     jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('3/19/25'),  diasContrato:155,  demissao:_parseDate('8/21/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/2/99')   },
  { matricula:'0136', nome:'Marcos Vinícios Abade de Sousa (anterior)', situacao:'DESLIGADO', jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 2',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('3/19/25'),  diasContrato:155,  demissao:_parseDate('8/21/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/27/00')  },
  { matricula:'2165', nome:'Marcos Wiliam Firmino Morais',             situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Renato',      admissao:_parseDate('12/16/25'), diasContrato:101,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/30/03')  },
  { matricula:'2164', nome:'Marcus Vinícius Dias Cunhas',              situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de PCP',                         horario:'Seg à Sex 09:30 às 19:00',                            lider:'Wesley Cruz', admissao:_parseDate('12/15/25'), diasContrato:102,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/24/98')  },
  { matricula:'2120', nome:'Mateus Gabriel Pereira de Oliveira',       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('4/24/25'),  diasContrato:168,  demissao:_parseDate('10/9/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/26/04') },
  { matricula:'2071', nome:'Matheus Guimarães Oliveira',               situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('9/4/24'),   diasContrato:58,   demissao:_parseDate('11/1/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/25/99') },
  { matricula:'2101', nome:'Matheus Santos Carneiro',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('2/5/25'),   diasContrato:415,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/7/96')   },
  { matricula:'3058', nome:'Melissa Kristina dos Santos',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedora',                                 horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('8/29/24'),  diasContrato:32,   demissao:_parseDate('9/30/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/8/97')   },
  { matricula:'2115', nome:'Miguel Abade Almeida de Araujo',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('3/7/25'),   diasContrato:385,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/24/05')  },
  { matricula:'2070', nome:'Miguel Lucas Barbosa',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('9/5/24'),   diasContrato:43,   demissao:_parseDate('10/18/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/21/81')  },
  { matricula:'2145', nome:'Mihara Lorrana Medeiros Rodrigues',        situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de Recrutamento e Seleção',      horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('9/10/25'),  diasContrato:198,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/8/69')   },
  { matricula:'2074', nome:'Murillo Ribeiro Meneses',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('9/19/24'),  diasContrato:326,  demissao:_parseDate('8/11/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/4/06')   },
  { matricula:'2063', nome:'Murilo Mauricio de Melo',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('7/30/24'),  diasContrato:72,   demissao:_parseDate('10/10/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/18/97')  },
  { matricula:'3079', nome:'Nadir Maria dos Santos',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Auxiliar de Limpeza',                       horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('8/18/25'),  diasContrato:44,   demissao:_parseDate('10/1/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/7/00')  },
  { matricula:'2136', nome:'Nicolas Correa Mariano',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('8/9/25'),   diasContrato:51,   demissao:_parseDate('9/29/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/20/96') },
  { matricula:'2062', nome:'Pamela Gonçalves Moreira',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Analista de Recursos Humanos Junior',       horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('7/24/24'),  diasContrato:422,  demissao:_parseDate('9/19/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('5/21/04')  },
  { matricula:'2099', nome:'Paulo Antonio da Silva Nascimento',        situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('1/30/25'),  diasContrato:421,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/24/93')  },
  { matricula:'3065', nome:'Pedro Henrique Castro Silva',              situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Seg à Sex 08:00 às 17:00',                            lider:'Ademir',      admissao:_parseDate('1/22/25'),  diasContrato:128,  demissao:_parseDate('5/30/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/26/03') },
  { matricula:'2012', nome:'Rafael Gabriel Moraes',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('9/4/23'),   diasContrato:935,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/30/98') },
  { matricula:'2068', nome:'Rayan Nazario da Silva',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor',                                   horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('8/29/24'),  diasContrato:89,   demissao:_parseDate('11/26/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/20/89')  },
  { matricula:'NT-P',  nome:'Reginaldo Floriano dos Santos',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('10/8/24'),  diasContrato:42,   demissao:_parseDate('11/19/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('6/27/90')  },
  { matricula:'2140', nome:'Renan Oliveira da Silva',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Vendas',         cargo:'Vendedor',                                  horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Davi',        admissao:_parseDate('8/15/25'),  diasContrato:28,   demissao:_parseDate('9/12/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/16/94') },
  { matricula:'3081', nome:'Renato Rodrigues Gomes',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('8/26/25'),  diasContrato:44,   demissao:_parseDate('10/9/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/18/94') },
  { matricula:'2020', nome:'Renato Silva Domingues',                   situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 3',                    horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Carlos',      admissao:_parseDate('10/2/23'),  diasContrato:907,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/3/96')   },
  { matricula:'2003', nome:'Robert Ramos de Oliveira',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral 2',                          horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('4/3/23'),   diasContrato:641,  demissao:_parseDate('1/3/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/27/79')  },
  { matricula:'2171', nome:'Robson David Ferreira Souza Santos',       situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Renato',      admissao:_parseDate('3/12/26'),  diasContrato:15,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/14/02') },
  { matricula:'3053', nome:'Rodolfo Figueiredo',                       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Ajudante Geral 2',                          horario:'Seg à Sex 07:30 às 17:00',                            lider:'Ademir',      admissao:_parseDate('6/18/24'),  diasContrato:479,  demissao:_parseDate('10/10/25'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('4/4/67')   },
  { matricula:'2139', nome:'Rodrigo do Nascimento Rangel',             situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Operador de Calandra 1',                    horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Heleno',      admissao:_parseDate('8/16/25'),  diasContrato:223,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/7/92')   },
  { matricula:'2144', nome:'Rogerio de Andrade Quadros',               situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor 1',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('9/4/25'),   diasContrato:204,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/22/03') },
  { matricula:'2122', nome:'Ronaldo dos Santos Ramos',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'André',       admissao:_parseDate('5/6/25'),   diasContrato:89,   demissao:_parseDate('8/3/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/28/83')  },
  { matricula:'2076', nome:'Roniere Carneiro Lima',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Supervisora de RH/DP',                      horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Guilherme',   admissao:_parseDate('9/23/24'),  diasContrato:13,   demissao:_parseDate('10/6/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('2/8/03')   },
  { matricula:'2077', nome:'Rosemeire Halcsick',                       situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Líder de Produção',                         horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('9/23/24'),  diasContrato:550,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/1/72')   },
  { matricula:'2009', nome:'Samuel de Carvalho Bandez',                situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Carlos',      admissao:_parseDate('1/3/23'),   diasContrato:1004, demissao:_parseDate('10/3/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/31/05') },
  { matricula:'3057', nome:'Samuel Martins Silva',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Atendente',                                 horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('8/12/24'),  diasContrato:86,   demissao:_parseDate('11/6/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/3/92')   },
  { matricula:'2058', nome:'Shirlene Vieira Lino',                     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Auxiliar de Limpeza',                       horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Carlos',      admissao:_parseDate('7/17/24'),  diasContrato:618,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/16/95') },
  { matricula:'3071', nome:'Shirley Lopes Gomes',                      situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Facilities',     cargo:'Faxineira',                                 horario:'Seg à Sex 08:00 às 15:00 Sáb 08:00 às 12:00',        lider:'Adriano',     admissao:_parseDate('5/9/25'),   diasContrato:84,   demissao:_parseDate('8/1/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/28/00')  },
  { matricula:'NT-A',  nome:'Silvia Francisca Vilela',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente Administrativo',                 horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Carlos',      admissao:'',                     diasContrato:0,    demissao:_parseDate('9/18/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/26/91')  },
  { matricula:'2142', nome:'Sophia Cavichia da Silva',                 situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('8/27/25'),  diasContrato:44,   demissao:_parseDate('10/10/25'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/31/85')  },
  { matricula:'2169', nome:'Sophia Cavichia da Silva (recontratada)',  situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Assistente de Processos',                   horario:'Seg à Sex 08:30 às 18:00',                            lider:'Carlos',      admissao:_parseDate('3/3/26'),   diasContrato:24,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('10/31/05') },
  { matricula:'3084', nome:'Thaís de Cillo Silveira',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico Júnior',                   horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('9/29/25'),  diasContrato:179,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'3083', nome:'Tiago de Souza Oliveira',                  situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Designer',       cargo:'Designer Gráfico',                          horario:'Seg à Sex 07:30 às 17:00',                            lider:'Adriano',     admissao:_parseDate('9/3/25'),   diasContrato:205,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/2/04')   },
  { matricula:'2167', nome:'Tiago Pedro da Silva',                     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Ajudante de Expedição',                     horario:'Seg à Sex 07:30 às 16:30 Sáb 07:30 às 11:00',        lider:'Wesley Reis', admissao:_parseDate('1/27/26'),  diasContrato:59,   demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/7/01')   },
  { matricula:'2127', nome:'Tiago Pires de Sousa',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Supervisor de Produção',                    horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('5/28/25'),  diasContrato:90,   demissao:_parseDate('8/26/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/29/90') },
  { matricula:'2118', nome:'Toni Carlos Conceição Amorim',             situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Consultor',                                 horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('4/11/25'),  diasContrato:136,  demissao:_parseDate('8/25/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('12/31/01') },
  { matricula:'NT-V',  nome:'Valmir',                                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Vendas',         cargo:'Vendedor',                                  horario:'Freelancer',                                          lider:'Samuel',      admissao:'',                     diasContrato:0,    demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('7/24/80')  },
  { matricula:'3075', nome:'Victor Dias Taveira',                      situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Vinícios',    admissao:_parseDate('5/21/25'),  diasContrato:310,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/18/94') },
  { matricula:'2150', nome:'Victor Hugo Matos Barbosa',                situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Renato',      admissao:_parseDate('9/24/25'),  diasContrato:184,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/17/01')  },
  { matricula:'3063', nome:'Vinicios de Oliveira Rios',                situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Supervisor de Designer e Vendas',            horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('1/7/25'),   diasContrato:444,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/8/03')  },
  { matricula:'2064', nome:'Vitor Claudino Fidalgo',                   situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('8/2/24'),   diasContrato:223,  demissao:_parseDate('3/13/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/7/96')   },
  { matricula:'2083', nome:'Vitor Claudio Barreira Tedaldi',           situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Vendas',         cargo:'Vendedor',                                  horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Samuel',      admissao:_parseDate('10/16/24'), diasContrato:44,   demissao:_parseDate('11/29/24'),   tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('1/31/96')  },
  { matricula:'2160', nome:'Vitor da Silva Mauro',                     situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Seg à Sex 07:30 às 17:00',                            lider:'Vinícios',    admissao:_parseDate('12/1/25'),  diasContrato:116,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('3/2/98')   },
  { matricula:'2100', nome:'Vitor Henrique Bezerra da Silva',          situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Facilities',     cargo:'Ajudante Geral',                            horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Toni',        admissao:_parseDate('1/31/25'),  diasContrato:152,  demissao:_parseDate('7/2/25'),     tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('8/9/95')   },
  { matricula:'3086', nome:'Vitor Reyel Soares Lopes',                 situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Produção',       cargo:'Ajudante de Produção',                      horario:'Seg à Sex 08:00 às 17:00 Sáb 08:00 às 12:00',        lider:'Ademir',      admissao:_parseDate('10/13/25'), diasContrato:165,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('9/29/01')  },
  { matricula:'3085', nome:'Wei Zhou',                                 situacao:'ATIVO',      jornada:'CLT', matriz:'NT-JX', setor:'Vendas',         cargo:'Vendedor',                                  horario:'Art. 62',                                             lider:'Patrícia',    admissao:_parseDate('9/29/25'),  diasContrato:179,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:_parseDate('11/25/06') },
  { matricula:'2138', nome:'Wendel Rocha Lockmann',                    situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Revisor',                                   horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('8/13/25'),  diasContrato:44,   demissao:_parseDate('9/26/25'),    tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2027', nome:'Wesley Brandão dos Santos',                situacao:'DESLIGADO',  jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Expedidor de Mercadorias',                  horario:'Escala 12x36 - Diurno 07:30 às 19:30',               lider:'Samuel',      admissao:_parseDate('2/1/24'),   diasContrato:236,  demissao:_parseDate('9/24/24'),    tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2072', nome:'Wesley Reis da Silva',                     situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Expedição',      cargo:'Encarregado de Expedição',                  horario:'Seg à Qui 7:30 às 17:00 e Sex até 16:30',            lider:'Carlos',      admissao:_parseDate('9/11/24'),  diasContrato:562,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'0012', nome:'Wesley Vitor Souza Cruz',                  situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Administrativo', cargo:'Supervisor de PCP',                         horario:'Seg à Sex 07:30 às 17:00',                            lider:'Carlos',      admissao:_parseDate('7/3/23'),   diasContrato:998,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     },
  { matricula:'2108', nome:'Yuri Gomes Cardoso',                       situacao:'ATIVO',      jornada:'CLT', matriz:'NT',    setor:'Produção',       cargo:'Impressor Digital 1',                       horario:'Escala 12x36 - Noturno 07:30 às 19:30',              lider:'Rogério',     admissao:_parseDate('2/18/25'),  diasContrato:402,  demissao:'',                       tipoExame:'', dataExame:'', telefone:'', nascimento:''                     }
];

window.getHREmployees = function() {
  return (window._cache && window._cache.hrEmployees && window._cache.hrEmployees.length > 0)
    ? window._cache.hrEmployees
    : window.HR_EMPLOYEES_SEED;
};

window.saveHREmployees = function(arr) {
  if (!window._cache) window._cache = {};
  window._cache.hrEmployees = arr;
};
